# Jekyll Site Configuration for Soumith's Blog & Shelf
title: "Soumith"
email: "soumithhh@gmail.com"
description: "Personal blog and bookshelf"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Markdown Engine
markdown: kramdown
highlighter: rouge

# Collections
collections:
  books:
    output: true
    permalink: /shelf/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclusions
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
